use_frameworks!

target 'RCAlertController_Example' do
  pod 'RCAlertController', :path => '../'

  target 'RCAlertController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
